<template><div><h1 id="wav文件解析" tabindex="-1"><a class="header-anchor" href="#wav文件解析"><span>Wav文件解析</span></a></h1>
<h2 id="一、riff文件结构" tabindex="-1"><a class="header-anchor" href="#一、riff文件结构"><span>一、RIFF文件结构</span></a></h2>
<p>要了解<strong>wav</strong>文件，首先要了解<strong>RIFF</strong>文件格式</p>
<p><strong>资源交换文件格式(Resource Interchange File Format,RIFF)</strong> 是由Microsoft与IBM提出的一种文件格式标准。RIFF文件由头部Header + 多个Chunks 组成，如下图所示</p>
<h3 id="_1、riff表头-header" tabindex="-1"><a class="header-anchor" href="#_1、riff表头-header"><span>1、RIFF表头(Header)</span></a></h3>
<p><img src="@source/notes/游戏开发/程序设计/Wav文件解析/res/pic_01.jpg" alt="RIFF Chunk" title="RIFF Chunk"></p>
<p><strong>对应代码：</strong></p>
<div class="language-csharp line-numbers-mode" data-ext="cs" data-title="cs"><pre v-pre class="language-csharp"><code><span class="token doc-comment comment">/// <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>summary</span><span class="token punctuation">></span></span></span>
<span class="token doc-comment comment">/// RIFF头部Chunk</span>
<span class="token doc-comment comment">/// <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>summary</span><span class="token punctuation">></span></span></span>
<span class="token keyword">private</span> <span class="token keyword">class</span> <span class="token class-name">RIFFChunk</span>
<span class="token punctuation">{</span>
    <span class="token keyword">public</span> <span class="token class-name"><span class="token keyword">string</span></span> id<span class="token punctuation">;</span>       <span class="token comment">//"RIFF"</span>
    <span class="token keyword">public</span> <span class="token class-name"><span class="token keyword">int</span></span> size<span class="token punctuation">;</span>        <span class="token comment">//size:（fileSize - id - size）</span>
    <span class="token keyword">public</span> <span class="token class-name"><span class="token keyword">string</span></span> type<span class="token punctuation">;</span>     <span class="token comment">//"AVI" or "WAV"</span>

    <span class="token keyword">public</span> <span class="token function">RIFFChunk</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">byte</span><span class="token punctuation">[</span><span class="token punctuation">]</span></span> data<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">int</span></span> off <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">)</span>
    <span class="token punctuation">{</span>
        id      <span class="token operator">=</span> <span class="token function">ToASCIIString</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> off <span class="token operator">+</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        size    <span class="token operator">=</span> <span class="token function">ToInt32</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> off <span class="token operator">+</span> <span class="token number">4</span><span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        type    <span class="token operator">=</span> <span class="token function">ToASCIIString</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> off <span class="token operator">+</span> <span class="token number">8</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2、子区块-subchunks" tabindex="-1"><a class="header-anchor" href="#_2、子区块-subchunks"><span>2、子区块(SubChunks)</span></a></h3>
<p><img src="@source/notes/游戏开发/程序设计/Wav文件解析/res/pic_02.jpg" alt="Sub Chunk" title="Sub Chunk"></p>
<p><strong>对应代码：</strong></p>
<div class="language-csharp line-numbers-mode" data-ext="cs" data-title="cs"><pre v-pre class="language-csharp"><code><span class="token doc-comment comment">/// <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>summary</span><span class="token punctuation">></span></span></span>
<span class="token doc-comment comment">/// SubChunk</span>
<span class="token doc-comment comment">/// <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>summary</span><span class="token punctuation">></span></span></span>
<span class="token keyword">private</span> <span class="token keyword">class</span> <span class="token class-name">SubChunk</span>
<span class="token punctuation">{</span>
    <span class="token keyword">public</span> <span class="token class-name"><span class="token keyword">string</span></span> id<span class="token punctuation">;</span>               <span class="token comment">//Chunk 类型</span>
    <span class="token keyword">public</span> <span class="token class-name"><span class="token keyword">int</span></span> size<span class="token punctuation">;</span>                <span class="token comment">//Chunk 大小</span>
    <span class="token keyword">public</span> <span class="token class-name"><span class="token keyword">int</span></span> next<span class="token punctuation">;</span>                <span class="token comment">//下一位索引</span>

    <span class="token keyword">public</span> <span class="token function">SubChunk</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">byte</span><span class="token punctuation">[</span><span class="token punctuation">]</span></span> data<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">int</span></span> off<span class="token punctuation">)</span>
    <span class="token punctuation">{</span>
        id <span class="token operator">=</span> <span class="token function">ToASCIIString</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> off <span class="token operator">+</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        size <span class="token operator">=</span> <span class="token function">ToInt32</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> off <span class="token operator">+</span> <span class="token number">4</span><span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        next <span class="token operator">=</span> off <span class="token operator">+</span> <span class="token number">8</span> <span class="token operator">+</span> size<span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>注意：</strong> 包括所有表头在内，所有Chunk的ID都是ASCII编码的4个字符（即4byte数据），并且使用的是<strong>小端序</strong>，要读出<strong>Int32</strong>的话请使用示例代码中的 <strong>ToInt32(data, index, true)</strong> 进行反转。</p>
<h2 id="二、wave-文件的区块信息" tabindex="-1"><a class="header-anchor" href="#二、wave-文件的区块信息"><span>二、WAVE 文件的区块信息</span></a></h2>
<h3 id="_1、-fmt-区块" tabindex="-1"><a class="header-anchor" href="#_1、-fmt-区块"><span>1、&quot;fmt &quot; 区块</span></a></h3>
<p>解析文件RIFF头部Chunk时，可以区分出WAVE文件，接着可以在数据中找到 <strong>&quot;fmt &quot;</strong> (注意这是4字节数据，包含1个字节的空格)的数据块，通过该区块来获取音频信息的采样率、通道数等信息。</p>
<p>fmt chunk的几个重要的信息</p>
<ol>
<li>channels 声道数，一般单声道或双声道</li>
<li>sampleRate 音频采样频率，这代表这每秒有多少个音频样本</li>
<li>bitsPerSample 采样位数，这代表着每个音频数据占用的bit位，除以8就是采样字节数，占用的byte字节</li>
</ol>
<p>$音频总时常 = \frac{(文件总字节数 - 数据起始位)}{(通道数 \times 采样字节数 \times 音频采样频率)}$</p>
<p><img src="@source/notes/游戏开发/程序设计/Wav文件解析/res/pic_03.jpg" alt="fmt Chunk" title="fmt Chunk"></p>
<p><strong>对应代码：</strong></p>
<div class="language-csharp line-numbers-mode" data-ext="cs" data-title="cs"><pre v-pre class="language-csharp"><code><span class="token doc-comment comment">/// <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>summary</span><span class="token punctuation">></span></span></span>
<span class="token doc-comment comment">/// "fmt " Chunk</span>
<span class="token doc-comment comment">/// <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>summary</span><span class="token punctuation">></span></span></span>
<span class="token keyword">private</span> <span class="token keyword">class</span> <span class="token class-name">FormatChunk</span> <span class="token punctuation">:</span> <span class="token type-list"><span class="token class-name">SubChunk</span></span>
<span class="token punctuation">{</span>
    <span class="token keyword">public</span> <span class="token class-name"><span class="token keyword">short</span></span> format<span class="token punctuation">;</span>            <span class="token comment">//音频格式：PCM = 1</span>
    <span class="token keyword">public</span> <span class="token class-name"><span class="token keyword">short</span></span> channels<span class="token punctuation">;</span>          <span class="token comment">//声道数</span>
    <span class="token keyword">public</span> <span class="token class-name"><span class="token keyword">int</span></span> sampleRate<span class="token punctuation">;</span>          <span class="token comment">//采样率</span>
    <span class="token keyword">public</span> <span class="token class-name"><span class="token keyword">int</span></span> byteRate<span class="token punctuation">;</span>            <span class="token comment">//每秒字节数</span>
    <span class="token keyword">public</span> <span class="token class-name"><span class="token keyword">short</span></span> blockAlign<span class="token punctuation">;</span>        <span class="token comment">//区块对齐</span>
    <span class="token keyword">public</span> <span class="token class-name"><span class="token keyword">short</span></span> bitsPerSample<span class="token punctuation">;</span>     <span class="token comment">//采样位数</span>

    <span class="token keyword">public</span> <span class="token function">FormatChunk</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">byte</span><span class="token punctuation">[</span><span class="token punctuation">]</span></span> data<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">int</span></span> off <span class="token operator">=</span> <span class="token number">12</span><span class="token punctuation">)</span> <span class="token punctuation">:</span> <span class="token keyword">base</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> off<span class="token punctuation">)</span>
    <span class="token punctuation">{</span>
        format          <span class="token operator">=</span> <span class="token function">ToInt16</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> off <span class="token operator">+</span>  <span class="token number">8</span><span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        channels        <span class="token operator">=</span> <span class="token function">ToInt16</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> off <span class="token operator">+</span> <span class="token number">10</span><span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        sampleRate      <span class="token operator">=</span> <span class="token function">ToInt32</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> off <span class="token operator">+</span> <span class="token number">12</span><span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        byteRate        <span class="token operator">=</span> <span class="token function">ToInt32</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> off <span class="token operator">+</span> <span class="token number">16</span><span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        blockAlign      <span class="token operator">=</span> <span class="token function">ToInt16</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> off <span class="token operator">+</span> <span class="token number">20</span><span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        bitsPerSample   <span class="token operator">=</span> <span class="token function">ToInt16</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> off <span class="token operator">+</span> <span class="token number">22</span><span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2、-data-区块" tabindex="-1"><a class="header-anchor" href="#_2、-data-区块"><span>2、&quot;data&quot; 区块</span></a></h3>
<p>data区块就是我们需要的音频数据，除了id和size，就只有data了</p>
<div class="language-csharp line-numbers-mode" data-ext="cs" data-title="cs"><pre v-pre class="language-csharp"><code><span class="token keyword">private</span> <span class="token keyword">class</span> <span class="token class-name">DataChunk</span> <span class="token punctuation">:</span> <span class="token type-list"><span class="token class-name">SubChunk</span></span>
<span class="token punctuation">{</span>
    <span class="token keyword">public</span> <span class="token function">DataChunk</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">byte</span><span class="token punctuation">[</span><span class="token punctuation">]</span></span> data<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">int</span></span> off <span class="token operator">=</span> <span class="token number">36</span><span class="token punctuation">)</span> <span class="token punctuation">:</span> <span class="token keyword">base</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> off<span class="token punctuation">)</span> <span class="token punctuation">{</span> <span class="token punctuation">}</span>
<span class="token punctuation">}</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="三、在unity中转化成audioclip" tabindex="-1"><a class="header-anchor" href="#三、在unity中转化成audioclip"><span>三、在Unity中转化成AudioClip</span></a></h2>
<p>在Unity中，我们可以通过 <strong>AudioClip.Create</strong> 方法来自定义创建，通过<strong>SetData</strong>或使用<strong>pcmreadercallback</strong> 回调来采样数据。采样时需要注意以下几点：</p>
<ol>
<li>双声道数据左右声道是交替存放</li>
<li>由于Unity的AudioClip已经处理了单双声道的采样，我们直接设置采样数据即可</li>
</ol>
<p><img src="@source/notes/游戏开发/程序设计/Wav文件解析/res/pic_04.jpg" alt="声道采样"></p>
<p><strong>示例代码</strong></p>
<div class="language-csharp line-numbers-mode" data-ext="cs" data-title="cs"><pre v-pre class="language-csharp"><code><span class="token keyword">public</span> <span class="token return-type class-name"><span class="token keyword">void</span></span> <span class="token function">CreateAudioClip</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token punctuation">{</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>riffChunk <span class="token operator">==</span> <span class="token keyword">null</span> <span class="token operator">||</span> formatChunk <span class="token operator">==</span> <span class="token keyword">null</span><span class="token punctuation">)</span>
    <span class="token punctuation">{</span>
        Debug<span class="token punctuation">.</span><span class="token function">LogError</span><span class="token punctuation">(</span><span class="token string">"No wav data to create AudioClip"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">return</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

    <span class="token comment">//Creat Audio Clip</span>
    <span class="token class-name"><span class="token keyword">int</span></span> channels <span class="token operator">=</span> formatChunk<span class="token punctuation">.</span>channels<span class="token punctuation">;</span>
    <span class="token class-name"><span class="token keyword">int</span></span> dataByte <span class="token operator">=</span> formatChunk<span class="token punctuation">.</span>bitsPerSample <span class="token operator">/</span> <span class="token number">8</span><span class="token punctuation">;</span>
    <span class="token class-name"><span class="token keyword">int</span></span> dataLength <span class="token operator">=</span> <span class="token punctuation">(</span>fileData<span class="token punctuation">.</span>Length <span class="token operator">-</span> dataStartIndex<span class="token punctuation">)</span> <span class="token operator">/</span> <span class="token punctuation">(</span>dataByte <span class="token operator">*</span> channels<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token class-name"><span class="token keyword">int</span></span> sampleRate <span class="token operator">=</span> formatChunk<span class="token punctuation">.</span>sampleRate<span class="token punctuation">;</span>
    <span class="token class-name"><span class="token keyword">string</span></span> fileName <span class="token operator">=</span> FileName<span class="token punctuation">;</span>
    audioClip <span class="token operator">=</span> AudioClip<span class="token punctuation">.</span><span class="token function">Create</span><span class="token punctuation">(</span>fileName<span class="token punctuation">,</span> dataLength<span class="token punctuation">,</span> channels<span class="token punctuation">,</span> sampleRate<span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">,</span> OnAudioRead<span class="token punctuation">,</span> OnAudioSetPosition<span class="token punctuation">)</span><span class="token punctuation">;</span>
    curPlayIndex <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>

    <span class="token comment">//Debug</span>
    Debug<span class="token punctuation">.</span><span class="token function">Log</span><span class="token punctuation">(</span>
        <span class="token interpolation-string"><span class="token string">$"Create Audio Clip: </span><span class="token interpolation"><span class="token punctuation">{</span><span class="token expression language-csharp">fileName</span><span class="token punctuation">}</span></span><span class="token string">"</span></span> <span class="token operator">+</span>
        <span class="token interpolation-string"><span class="token string">$"\n\tformat: </span><span class="token interpolation"><span class="token punctuation">{</span><span class="token expression language-csharp">formatChunk<span class="token punctuation">.</span>id</span><span class="token punctuation">}</span></span><span class="token string">"</span></span> <span class="token operator">+</span>
        <span class="token interpolation-string"><span class="token string">$"\n\tchannel: </span><span class="token interpolation"><span class="token punctuation">{</span><span class="token expression language-csharp">formatChunk<span class="token punctuation">.</span>channels</span><span class="token punctuation">}</span></span><span class="token string">"</span></span> <span class="token operator">+</span>
        <span class="token interpolation-string"><span class="token string">$"\n\tsampleByte: </span><span class="token interpolation"><span class="token punctuation">{</span><span class="token expression language-csharp">dataByte</span><span class="token punctuation">}</span></span><span class="token string">"</span></span> <span class="token operator">+</span>
        <span class="token interpolation-string"><span class="token string">$"\n\tsampleRate </span><span class="token interpolation"><span class="token punctuation">{</span><span class="token expression language-csharp">formatChunk<span class="token punctuation">.</span>sampleRate</span><span class="token punctuation">}</span></span><span class="token string">"</span></span> <span class="token operator">+</span>
        <span class="token interpolation-string"><span class="token string">$"\n\ttotal: </span><span class="token interpolation"><span class="token punctuation">{</span><span class="token expression language-csharp">fileData<span class="token punctuation">.</span>Length</span><span class="token punctuation">}</span></span><span class="token string">"</span></span> <span class="token operator">+</span>
        <span class="token interpolation-string"><span class="token string">$"\n\tsample: </span><span class="token interpolation"><span class="token punctuation">{</span><span class="token expression language-csharp">dataLength</span><span class="token punctuation">}</span></span><span class="token string">"</span></span> <span class="token operator">+</span>
        <span class="token interpolation-string"><span class="token string">$"\n\tstartIndex: </span><span class="token interpolation"><span class="token punctuation">{</span><span class="token expression language-csharp">dataStartIndex</span><span class="token punctuation">}</span></span><span class="token string">"</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>

<span class="token return-type class-name"><span class="token keyword">void</span></span> <span class="token function">OnAudioRead</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">float</span><span class="token punctuation">[</span><span class="token punctuation">]</span></span> data<span class="token punctuation">)</span>
<span class="token punctuation">{</span>
    <span class="token keyword">for</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">int</span></span> i <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> i <span class="token operator">&lt;</span> data<span class="token punctuation">.</span>Length<span class="token punctuation">;</span> i<span class="token operator">++</span><span class="token punctuation">)</span>
    <span class="token punctuation">{</span>
        <span class="token class-name"><span class="token keyword">int</span></span> dataIndex <span class="token operator">=</span> dataStartIndex <span class="token operator">+</span> curPlayIndex <span class="token operator">*</span> <span class="token number">2</span><span class="token punctuation">;</span><span class="token comment">//dataByte=2</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>dataIndex <span class="token operator">&lt;</span> fileData<span class="token punctuation">.</span>Length <span class="token operator">-</span> <span class="token number">1</span><span class="token punctuation">)</span>
        <span class="token punctuation">{</span>
            data<span class="token punctuation">[</span>i<span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token function">BytesToFloat01</span><span class="token punctuation">(</span>fileData<span class="token punctuation">[</span>dataIndex<span class="token punctuation">]</span><span class="token punctuation">,</span> fileData<span class="token punctuation">[</span>dataIndex <span class="token operator">+</span> <span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            curPlayIndex<span class="token operator">++</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        <span class="token keyword">else</span>
        <span class="token punctuation">{</span>
            data<span class="token punctuation">[</span>i<span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>

<span class="token return-type class-name"><span class="token keyword">void</span></span> <span class="token function">OnAudioSetPosition</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">int</span></span> newIndex<span class="token punctuation">)</span>
<span class="token punctuation">{</span>
    curPlayIndex <span class="token operator">=</span> newIndex<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="四、代码示例" tabindex="-1"><a class="header-anchor" href="#四、代码示例"><span>四、代码示例</span></a></h2>
<h3 id="_1、解析区块代码" tabindex="-1"><a class="header-anchor" href="#_1、解析区块代码"><span>1、解析区块代码</span></a></h3>
<p>在开发过程中，发现遇到了名为JUNK的垃圾区块，这种区块没有数据，可以跳过</p>
<div class="language-csharp line-numbers-mode" data-ext="cs" data-title="cs"><pre v-pre class="language-csharp"><code><span class="token preprocessor property">#<span class="token directive keyword">region</span> Data Chunk Process</span>
<span class="token keyword">public</span> <span class="token return-type class-name"><span class="token keyword">void</span></span> <span class="token function">ProcessData</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token punctuation">{</span>
    <span class="token comment">//RIFF Chunk</span>
    riffChunk <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token constructor-invocation class-name">RIFFChunk</span><span class="token punctuation">(</span>fileData<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>riffChunk<span class="token punctuation">.</span>id <span class="token operator">!=</span> <span class="token string">"RIFF"</span><span class="token punctuation">)</span>
    <span class="token punctuation">{</span>
        Debug<span class="token punctuation">.</span><span class="token function">LogError</span><span class="token punctuation">(</span><span class="token string">"File is not RIFF file:"</span> <span class="token operator">+</span> riffChunk<span class="token punctuation">.</span>id<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">return</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>riffChunk<span class="token punctuation">.</span>type <span class="token operator">!=</span> <span class="token string">"WAVE"</span><span class="token punctuation">)</span>
    <span class="token punctuation">{</span>
        Debug<span class="token punctuation">.</span><span class="token function">LogError</span><span class="token punctuation">(</span><span class="token string">"File is not WAVE file:"</span> <span class="token operator">+</span> riffChunk<span class="token punctuation">.</span>type<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">return</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

    <span class="token comment">//Read Chunks</span>
    <span class="token class-name"><span class="token keyword">int</span></span> index <span class="token operator">=</span> <span class="token number">12</span><span class="token punctuation">;</span>
    <span class="token keyword">do</span>
    <span class="token punctuation">{</span>
        <span class="token class-name">SubChunk</span> subChunk <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token constructor-invocation class-name">SubChunk</span><span class="token punctuation">(</span>fileData<span class="token punctuation">,</span> index<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>subChunk<span class="token punctuation">.</span>id <span class="token operator">==</span> <span class="token string">"JUNK"</span><span class="token punctuation">)</span>
        <span class="token punctuation">{</span>
            <span class="token comment">//JUNK Chunk，Skip</span>
        <span class="token punctuation">}</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>subChunk<span class="token punctuation">.</span>id <span class="token operator">==</span> <span class="token string">"fmt "</span><span class="token punctuation">)</span>
        <span class="token punctuation">{</span>
            formatChunk <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token constructor-invocation class-name">FormatChunk</span><span class="token punctuation">(</span>fileData<span class="token punctuation">,</span> index<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>subChunk<span class="token punctuation">.</span>id <span class="token operator">==</span> <span class="token string">"data"</span><span class="token punctuation">)</span>
        <span class="token punctuation">{</span>
            dataChunk <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token constructor-invocation class-name">DataChunk</span><span class="token punctuation">(</span>fileData<span class="token punctuation">,</span> index<span class="token punctuation">)</span><span class="token punctuation">;</span>
            dataStartIndex <span class="token operator">=</span> index <span class="token operator">+</span> <span class="token number">8</span><span class="token punctuation">;</span>
            <span class="token keyword">break</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        index <span class="token operator">=</span> subChunk<span class="token punctuation">.</span>next<span class="token punctuation">;</span>
    <span class="token punctuation">}</span> <span class="token keyword">while</span> <span class="token punctuation">(</span>index <span class="token operator">&lt;</span> fileData<span class="token punctuation">.</span>Length<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token preprocessor property">#<span class="token directive keyword">endregion</span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2、辅助工具代码" tabindex="-1"><a class="header-anchor" href="#_2、辅助工具代码"><span>2、辅助工具代码</span></a></h3>
<div class="language-csharp line-numbers-mode" data-ext="cs" data-title="cs"><pre v-pre class="language-csharp"><code><span class="token preprocessor property">#<span class="token directive keyword">region</span> Tools</span>
<span class="token keyword">private</span> <span class="token keyword">static</span> <span class="token return-type class-name"><span class="token keyword">float</span></span> <span class="token function">BytesToFloat01</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">byte</span></span> first<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">byte</span></span> second<span class="token punctuation">)</span>
<span class="token punctuation">{</span>
    <span class="token class-name"><span class="token keyword">short</span></span> s <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token keyword">short</span><span class="token punctuation">)</span><span class="token punctuation">(</span><span class="token punctuation">(</span>second <span class="token operator">&lt;&lt;</span> <span class="token number">8</span><span class="token punctuation">)</span> <span class="token operator">|</span> first<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">return</span> s <span class="token operator">/</span> <span class="token number">32768.0f</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>

<span class="token keyword">public</span> <span class="token keyword">static</span> <span class="token return-type class-name"><span class="token keyword">string</span></span> <span class="token function">ToASCIIString</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">byte</span><span class="token punctuation">[</span><span class="token punctuation">]</span></span> data<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">int</span></span> index<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">int</span></span> cnt <span class="token operator">=</span> <span class="token number">4</span><span class="token punctuation">)</span>
<span class="token punctuation">{</span>
    <span class="token keyword">return</span> ASCIIEncoding<span class="token punctuation">.</span>ASCII<span class="token punctuation">.</span><span class="token function">GetString</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> index<span class="token punctuation">,</span> cnt<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>

<span class="token keyword">private</span> <span class="token keyword">static</span> <span class="token return-type class-name"><span class="token keyword">short</span></span> <span class="token function">ToInt16</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">byte</span><span class="token punctuation">[</span><span class="token punctuation">]</span></span> data<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">int</span></span> index<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">bool</span></span> reverse <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">)</span>
<span class="token punctuation">{</span>
    <span class="token class-name"><span class="token keyword">short</span></span> v<span class="token punctuation">;</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>reverse<span class="token punctuation">)</span>
    <span class="token punctuation">{</span>
        v <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token keyword">short</span><span class="token punctuation">)</span><span class="token punctuation">(</span><span class="token punctuation">(</span>data<span class="token punctuation">[</span>index <span class="token operator">+</span> <span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token operator">|</span> <span class="token punctuation">(</span>data<span class="token punctuation">[</span>index<span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token operator">&lt;&lt;</span> <span class="token number">8</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">else</span>
    <span class="token punctuation">{</span>
        v <span class="token operator">=</span> BitConverter<span class="token punctuation">.</span><span class="token function">ToInt16</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> index<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">return</span> v<span class="token punctuation">;</span>
<span class="token punctuation">}</span>


<span class="token keyword">private</span> <span class="token keyword">static</span> <span class="token return-type class-name"><span class="token keyword">int</span></span> <span class="token function">ToInt32</span><span class="token punctuation">(</span><span class="token class-name"><span class="token keyword">byte</span><span class="token punctuation">[</span><span class="token punctuation">]</span></span> data<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">int</span></span> index<span class="token punctuation">,</span> <span class="token class-name"><span class="token keyword">bool</span></span> reverse <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">)</span>
<span class="token punctuation">{</span>
    <span class="token class-name"><span class="token keyword">int</span></span> v<span class="token punctuation">;</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>reverse<span class="token punctuation">)</span>
    <span class="token punctuation">{</span>
        v <span class="token operator">=</span>   <span class="token punctuation">(</span>data<span class="token punctuation">[</span>index <span class="token operator">+</span> <span class="token number">3</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
            <span class="token operator">|</span> <span class="token punctuation">(</span>data<span class="token punctuation">[</span>index <span class="token operator">+</span> <span class="token number">2</span><span class="token punctuation">]</span>  <span class="token operator">&lt;&lt;</span> <span class="token number">8</span><span class="token punctuation">)</span>
            <span class="token operator">|</span> <span class="token punctuation">(</span>data<span class="token punctuation">[</span>index <span class="token operator">+</span> <span class="token number">1</span><span class="token punctuation">]</span>  <span class="token operator">&lt;&lt;</span> <span class="token number">16</span><span class="token punctuation">)</span>
            <span class="token operator">|</span> <span class="token punctuation">(</span>data<span class="token punctuation">[</span>index<span class="token punctuation">]</span>      <span class="token operator">&lt;&lt;</span> <span class="token number">24</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">else</span>
    <span class="token punctuation">{</span>
        v <span class="token operator">=</span> BitConverter<span class="token punctuation">.</span><span class="token function">ToInt32</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> index<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">return</span> v<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token preprocessor property">#<span class="token directive keyword">endregion</span></span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="五、参考链接" tabindex="-1"><a class="header-anchor" href="#五、参考链接"><span>五、参考链接</span></a></h2>
<p><a href="https://zh.wikipedia.org/zh-cn/%E8%B3%87%E6%BA%90%E4%BA%A4%E6%8F%9B%E6%AA%94%E6%A1%88%E6%A0%BC%E5%BC%8F" target="_blank" rel="noopener noreferrer">RIFF文件Wiki<ExternalLinkIcon/></a></p>
<p><a href="https://www.cnblogs.com/cheney23reg/archive/2010/08/08/1795067.html" target="_blank" rel="noopener noreferrer">wav、pcm数据格式<ExternalLinkIcon/></a></p>
<p><a href="https://github.com/DarkNest/WavForUnity.git" target="_blank" rel="noopener noreferrer">WavForUnity github<ExternalLinkIcon/></a></p>
</div></template>


